trigger:
  - none

variables:
  - group : spnvars
  - group : trfvars
  
  
pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: Setup
  jobs:
    - job: Setup
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '1.3.9'
- stage: Plan_Dev
  dependsOn: [Setup]
  jobs:
    - job: Plan_Dev
      steps:
      - script: |

              az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
              terraform init -backend-config="storage_account_name=$(tfBackendStorageAccountName)" -backend-config="container_name=$(tfBackendStorageContainerName)" -backend-config="access_key=$(tfBackendSAAccessKey)" -backend-config="key=$(tfBackendFileName)-dev"
              
      - script: |
              terraform plan -var-file="./infra/terraform.tfvars" -out="out.plan" -var="client_id=$(client_id)" -var="client_secret=$(client_secret)" -var="tenant_id=$(tenant_id)" -var="subscription_id=$(subscription_id)"
      - script: |

              # terraform apply -var-file="./infra/terraform.tfvars" -out="out.plan" -var="client_id=$(client_id)" -var="client_secret=$(client_secret)" -var="tenant_id=$(tenant_id)" -var="subscription_id=$(subscription_id)"
    

